# Allows whoever equips it to become invisible from players. Cannot be repaired or enchanted, and probably shouldn't be
# used in crafting.
# The invisibility is bypassed by the "aststrinkets.trinket.seeinvisible" permission.
invisibilityTunic:
  enabled: true

# The same as the invisibility tunic, except it has 10 durability left. Added just to have a less op version to give to
# players if you feel full durability is too much.
fragileInvisibilityTunic:
  enabled: true

# Note that this item's invisibility cannot be bypassed. It has to be unequipped to be able to see that player again.
# If you don't want that, it's better to either disable it or make sure it doesn't get to people who shouldn't have it.
# This trinket requires "aststrinkets.op" permission to give.
trueInvisibilityTunic:
  enabled: true

# An item that turns into another when not observed. Pretty safe to give around, the items it turns into aren't
# particularly dangerous.
# These items are forbidden from being used by default: items obtainable through commands only, unbreakable items,
# items that spawn entities (spawn eggs, infested blocks, minecarts etc.), buckets and totems of undying.
shapeShifter:
  enabled: true
  # This list allows you to add more items to the blacklist.
  # You can find them here https://jd.papermc.io/paper/1.16/org/bukkit/Material.html (or at the page corresponding to
  # the version you use).
  itemBlacklist: []

# A cake that gives a random effect of 30 seconds duration when a piece is eaten.
# This trinket is experimental, so it requires "aststrinkets.op" permission to give. It might not function properly.
mysteryCake:
  enabled: true
  # By default, the plugin checks the hunger of the player when determining if the cake is going to be eaten or not.
  # Set this to true if your server uses a plugin that makes food heal directly instead of through hunger.
  checkHealth: false

# The organ a spider uses to spin webs. Keep it in offhand while placing string, to place cobwebs instead.
spinneret:
  enabled: true

# Shift right click in your inventory while holding this item on any damaged item to bring it back to full durability.
# One time use.
mendingPowder:
  enabled: true

# Shift right click in your inventory while holding this item on other trinkets to bind them to you. This makes you the
# owner of that trinket, and no one else will be able to use it. Has no effect on the Shapeshifter or the Binding Powder
# itself. One time use.
bindingPowder:
  enabled: true

# Works the same way as the Binding Powder, except it removes the owner, if there's one. For obvious reasons, this
# requires "aststrinkets.op" permission to give.
unbindingPowder:
  enabled: true

# The wearer can see players who wear invisibility tunics. Cannot be repaired or enchanted, and probably shouldn't be
# used in crafting.
trueSightCap:
  enabled: true

# Inspired by an idea of Homen06. It removes mending from another item and becomes a Homendingdirt.
homendirt:
  enabled: true

# Inspired by an idea of Homen06. It applies mending to another item and is consumed after.
homendingdirt:
  enabled: true

# Right click an entity that has a baby form (and that isn't already a baby) to turn it into a baby.
youthMilk:
  enabled: true
  # Whether only the owner of a pet can turn it into a baby. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Right click a mob to trap it within the diamond. Able to trap any mob excluding withers and ender dragons.
# This is experimental.
diamondTrap:
  enabled: true
  # Whether only the owner of a pet can trap it. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Right click an animal to trap it within the emerald. Able to trap any animal, even the aggressive ones, but not
# undead animals.
# This is experimental.
emeraldTrap:
  enabled: true
  # Whether only the owner of a pet can trap it. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Right click a monster to trap it within the amethyst. Able to trap any monster excluding those with implied or obvious
# sentience (eg. illagers, endermen) and boss monsters (wither, ender dragon).
# This is experimental.
amethystTrap:
  enabled: true
  # Whether only the owner of a pet can trap it. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Right click a mob to trap it within the nether star. Able to trap any mob apart from the ender dragons. Unlike the
# others, it is not destroyed when the trapped creature is released.
# This is experimental.
netherStarTrap:
  enabled: true
  # Whether only the owner of a pet can trap it. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Shift right click in your inventory on a block to turn this trinket into an infinite source of that block for placing.
# Basically creative mode, but only for a single block.
# Players with permission aststrinkets.trinket.unboundinfinityitem are able to use this trinket on any block.
infinityItem:
  enabled: true
  # List of blocks you can add can be found here https://jd.papermc.io/paper/1.18/org/bukkit/Material.html
  # The trinket can only be used on the blocks specified here.
  allowedBlocks: [DIRT, STONE, COBBLESTONE, OAK_LOG, BIRCH_LOG, SPRUCE_LOG, JUNGLE_LOG, ACACIA_LOG, DARK_OAK_LOG,
                  CRIMSON_STEM, WARPED_STEM, DEEPSLATE, COBBLED_DEEPSLATE]

# A firework rocket that can be used to boost an elytra multiple times. On failure, the rocket is consumed. On critical
# failure, the rocket is consumed and an explosion equal in strength to 2 TNT is detonated at the player's location.
# The explosion can break blocks and set fire to them.
reignitableRocketPrototype:
  enabled: true
  # Percentage of uses that result in the rocket being consumed.
  failureChance: 33.33
  # Percentage of uses that result in the rocket exploding.
  criticalFailureChance: 1.0
  # An experimental setting that triggers a second explosion without a specific cause, which doesn't damage blocks or set
  # fire to them. Set this to true if you have something that stops players from taking damage from the original explosion,
  # and you want them to take damage as intended.
  # Warning: it can have some undesired side effects to nearby entities that are supposed to be protected from damage.
  pluginExplosion: false

# Works the same as the prototype, except it no longer causes explosions. On failure, it is simply consumed.
reignitableRocket:
  enabled: true
  # Percentage of uses that result in the rocket being consumed.
  failureChance: 10.0

# A firework rocket that can be reused to boost an elytra. It has no chance of failure.
# It needs "aststrinkets.op" permission to give.
perfectedReignitableRocket:
  enabled: true

# An arrow that will kill anything it manages to damage. If the arrow has no owner, it will work even if shot by a mob.
# If it has one though, it will only work if it is shot directly by the owner.
deathArrow:
  enabled: true

# Like the True Tunic of Invisibility, this is what I would call a completely unbalanced trinket you want to really
# take care with. Once it's shot and it hits something with health, whatever it hit will die. The only way to stop the
# arrow from killing something is by stopping the collision altogether, and not the damage as plugins usually do.
# It does follow the same rules as the Arrow of Death, if it has an owner, only the owner can use it directly, otherwise
# any entity can use it.
# Obviously it requires the "aststrinkets.op" permission to give.
trueDeathArrow:
  enabled: true

# An ender chest that lets you contain a shulker box "inside". This in turn allows you to put it in another shulker box.
# Does not work if the box has another containment unit inside. Contain a shulker box by using shift right click inside
# the inventory while holding the unit on cursor. Retrieve the box by either placing the unit or right clicking air while
# sneaking with the unit in either hand. One use only.
shulkerBoxContainmentUnit:
  enabled: true

# A helmet that prevents you from drowning when equipped. Does not prevent suffocation (when you are inside blocks).
# Entities can use it too.
divingHelmet:
  enabled: true

# Boots that prevent fall damage when equipped. Entities can use them too.
hydraulicBoots:
  enabled: true

# Right click a creature with it to make it invulnerable to most forms of damage. Can still be damaged by players in creative
# mode. Creatures made invulnerable using this trinket can be trapped or affected by similar trinkets, by the player that
# made them invulnerable.
# This trinket requires "aststrinkets.op" permission to give.
lifeWater:
  enabled: true
  # Whether only the owner of a pet can make it invulnerable. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: false

# A netherite sword that has a chance to "eat" a random enchantment of the equipment (armour + hands) of those it hits.
# It does so by lowering the level of the enchantment by 1, or by removing it if it would reach 0 or less.
# Only triggered if the hit has at least 90% of the cooldown passed.
souleater:
  enabled: true
  # The minimum time between two uses, in seconds.
  cooldown: 60
  # The chance that the Souleater will consume one of the enchants of those it strikes.
  eatChance: 1.0

# A random creature hatches from this egg when thrown.
# Note, it is supposed to always hatch something when thrown, but a bug might be preventing that.
mysteryEgg:
  enabled: true
  # These mobs should not spawn from the eggs.
  # A complete list of options can be found here: https://jd.papermc.io/paper/1.18/org/bukkit/entity/EntityType.html
  blacklist: [WITHER, ENDER_DRAGON]

# Hold in the other hand while fishing to reduce the time it takes to lure fish.
bait:
  enabled: true
  # Percentage reduced from the waiting time. Combined with lure 3, 50% makes fish appear immediately.
  efficiency: 50.0

# Right click air while sneaking to transfer your experience to this bottle and turn it into a Bottle o' Enchanting.
# Throw that bottle to gain back your experience.
experienceBottle:
  enabled: true

# An unbreakable iron axe that cuts trees logs and wood instantly but deals half the damage of a regular iron axe.
# Really loves to cut trees. If owned by a player, she doesn't enjoy being separated from them, nor does she appreciate
# being handled by strangers.
# Inspired by Lucy the Axe from Don't Starve Together.
# Requires the "aststrinkets.op" permission to give.
sentientAxe:
  enabled: true
