# Trinkets

# Allows whoever equips it to become invisible from players. Cannot be repaired or enchanted, and probably shouldn't be
# used in crafting.
# The invisibility is bypassed by the "aststrinkets.trinket.seeinvisible" permission.
invisibilityTunic:
  enabled: true

# The same as the invisibility tunic, except it has 10 durability left. Added just to have a less op version to give to
# players if you feel full durability is too much.
fragileInvisibilityTunic:
  enabled: true

# Note that this item's invisibility cannot be bypassed. It has to be unequipped to be able to see that player again.
# If you don't want that, it's better to either disable it or make sure it doesn't get to people who shouldn't have it.
# This trinket requires "aststrinkets.op" permission to give.
trueInvisibilityTunic:
  enabled: true

# An item that turns into another when not observed. Pretty safe to give around, the items it turns into aren't
# particularly dangerous.
# These items are forbidden from being used by default: items obtainable through commands only, unbreakable items,
# items that spawn entities (spawn eggs, infested blocks, minecarts etc.), buckets and totems of undying.
shapeShifter:
  enabled: true
  # This list allows you to add more items to the blacklist.
  # You can find them here https://jd.papermc.io/paper/1.16/org/bukkit/Material.html (or at the page corresponding to
  # the version you use).
  itemBlacklist: []

# A cake that gives a random effect of 30 seconds duration when a piece is eaten.
# This trinket is experimental, so it requires "aststrinkets.op" permission to give. It might not function properly.
mysteryCake:
  enabled: true
  # By default, the plugin checks the hunger of the player when determining if the cake is going to be eaten or not.
  # Set this to true if your server uses a plugin that makes food heal directly instead of through hunger.
  checkHealth: false

# The organ a spider uses to spin webs. Keep it in offhand while placing string, to place cobwebs instead.
spinneret:
  enabled: true

# Shift right click in your inventory while holding this item on any damaged item to bring it back to full durability.
# One time use.
# This trinket is experimental currently.
mendingPowder:
  enabled: true

# Shift right click in your inventory while holding this item on other trinkets to bind them to you. This makes you the
# owner of that trinket, and no one else will be able to use it. Has no effect on the Shapeshifter or the Binding Powder
# itself. One time use.
# This trinket is experimental.
bindingPowder:
  enabled: true

# Works the same way as the Binding Powder, except it removes the owner, if there's one. For obvious reasons, this
# requires "aststrinkets.op" permission to give.
unbindingPowder:
  enabled: true

# The wearer can see players who wear invisibility tunics. Cannot be repaired or enchanted, and probably shouldn't be
# used in crafting.
trueSightCap:
  enabled: true

# Inspired by Homen06. It removes mending from another item and becomes a Homendingdirt. This trinket is experimental.
homendirt:
  enabled: true

# Inspired by Homen06. It applies mending to another item and is consumed after. This trinket is experimental.
homendingdirt:
  enabled: true

# Right click an entity that has a baby form (and that isn't already a baby) to turn it into a baby.
youthMilk:
  enabled: true
  # Whether only the owner of a pet can turn it into a baby. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Right click a mob to trap it within the diamond. Able to trap any mob excluding withers and ender dragons.
# This is experimental.
diamondTrap:
  enabled: true
  # Whether only the owner of a pet can trap it. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Right click an animal to trap it within the emerald. Able to trap any animal, even the aggressive ones, but not
# undead animals.
# This is experimental.
emeraldTrap:
  enabled: true
  # Whether only the owner of a pet can trap it. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Right click a monster to trap it within the amethyst. Able to trap any monster excluding those with implied or obvious
# sentience (eg. illagers, endermen) and boss monsters (wither, ender dragon).
# This is experimental.
amethystTrap:
  enabled: true
  # Whether only the owner of a pet can trap it. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Right click a mob to trap it within the nether star. Able to trap any mob apart from the ender dragons. Unlike the
# others, it is not destroyed when the trapped creature is released.
# This is experimental.
netherStarTrap:
  enabled: true
  # Whether only the owner of a pet can trap it. Bypassed with aststrinkets.trinket.ignorepetowner.
  petOwnerOnly: true

# Shift right click in your inventory on a block to turn this trinket into an infinite source of that block for placing.
# Basically creative mode, but only for a single block.
# Players with permission aststrinkets.trinket.unboundinfinityitem are able to use this trinket on any block.
# This trinket is, too, experimental.
infinityItem:
  enabled: true
  # List of blocks you can add can be found here https://jd.papermc.io/paper/1.18/org/bukkit/Material.html
  # The trinket can only be used on the blocks specified here.
  allowedBlocks: [DIRT, STONE, COBBLESTONE, OAK_LOG, BIRCH_LOG, SPRUCE_LOG, JUNGLE_LOG, ACACIA_LOG, DARK_OAK_LOG,
                  CRIMSON_STEM, WARPED_STEM, DEEPSLATE, COBBLED_DEEPSLATE]