name: AstsTrinkets
main: com.astelon.aststrinkets.AstsTrinkets
version: '1.0.0-beta.3'
author: Astelon
api-version: '1.18'
commands:
  trinkets:
    description: Base command for Ast's Trinkets plugin.
permissions:
  aststrinkets.op:
    description: Special permission for giving trinkets that don't obey to normal limitations.
    default: op
    children:
      aststrinkets.admin: true
  aststrinkets.admin:
    description: Gives access to all commands as well as other admin features of the plugin.
    default: op
    children:
      aststrinkets.command.give: true
      aststrinkets.command.clear: true
      aststrinkets.command.reload: true
      aststrinkets.command.help: true

      aststrinkets.trinket.seeinvisible: true
      aststrinkets.trinket.unboundinfinityitem: true
      aststrinkets.trinket.ignorepetowner: true
      aststrinkets.trinket.ignoreinvulnerable: true

  # Command permissions
  aststrinkets.command.give:
    description: Allows using the give command.
  aststrinkets.command.clear:
    description: Allows using the clear command.
  aststrinkets.command.reload:
    description: Allows using the reload command.
  aststrinkets.command.help:
    description: Allows using the help command.
    default: true

  # Trinket permissions
  aststrinkets.trinket.seeinvisible:
    description: Allows seeing players invisible from some trinkets.
  aststrinkets.trinket.unboundinfinityitem:
    description: Allows binding the infinity item to any block.
  aststrinkets.trinket.ignorepetowner:
    description: Allows using state changing trinkets (like the crystal traps or youth milk) on pets of other players.
  aststrinkets.trinket.ignoreinvulnerable:
    description: Allows using state changing trinkets on any invulnerable creature. You probably shouldn't though.